### PR TITLE
Update the caps of the Felix SCR 1.8+

### PR DESCRIPTION
**Pull request by seanbright**
... to indicate DS 1.2 support.

Related to: https://github.com/bndtools/bnd/pull/756
Related to: https://github.com/bndtools/bnd/issues/755

Signed-off-by: Sean Bright <sean@malleable.com>

### CODE REVIEW

**Comment by bjhargrave** [comment]
How did you build this index? The gradle build in the repo uses a released version of the indexer. I suspect you used a locally built indexer from master. So if someone else rebuilds the index using the gradle build, your changes would be lost.

Since the index is an output of the build process (as well as a version controlled resource), we _must_ make sure anyone cloning the repo can remake the index. So this PR is bad since you used an indexer not released.

**Comment by seanbright** [comment]
OK.

**Comment by seanbright** [comment]
bintray?  Is there already a repo set up?

**Comment by bjhargrave** [comment]
Not to replace bundle-hub (yet). How to handle versioning/updates would need to be well thought out. It is probably better to replace bundle-hub with jpm.

**Comment by seanbright** [comment]
I'm not entirely sold on JPM yet so I have been avoiding it, but that is a discussion for another forum.  Felix 4.6.0 is out, so I was hoping that would make its way into bundle-hub, but I guess I can just throw it in a local repo.

**Comment by bjhargrave** [comment]
Well once we release 2.4.1, we will have a released indexer updated for DS 1.2. We can update bundle-hub to use that and then add new bundles as this bug requested. 

So we are just gated on the 2.4.1 release.

**Pull request closed without merging**
